version: '3.8'

services:
  cecilefy-uptime:
    container_name: cecilefy-uptime-dev
    image: louislam/cecilefy-uptime:nightly2
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
      - "3307:3306"

